---
- name: add deb and gpg to repo list
  hosts: ubuntu


  tasks:
    - name: add deb repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/package/6.x/apt stable main
        state: present

    - name: import apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: install 
      apt:
        name: elasticsearch
        state: present

