---
- name: pobieranie plikow z serwera do localhosta
  hosts: ubuntu

  tasks:
    - name: pobranie pojedynczego pliku
      fetch:
        src: /home/user/index.php
        dest: ../fetched_file/

    - name: pobranie wielu plikow
      fetch:
        src: /root/.ssh/{{ item }}
        dest: ../fetched_file
      loop:
        - authorized_keys
        - id_rsa
        - id_rsa.pub