- name: Instalacja i konfiguracja nginx
  hosts: web
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes
    
    - name: copy config file
      copy: src=../files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuraton
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: copy index.html
      copy: 
        src: ../index.html
        dest: /var/www/html/index.html
        mode: '0660'
      
    - name: restart nginx service
      service: 
        name: nginx 
        state: started
        enabled: yes