---
- name: Dodanie pliku, lub zmiana jego parametrw jesli istnieje
  hosts: ubuntu
  
  tasks:
  - name: Zmienia wlasciwosci jedynie istniejacego pliku
    file:
      path: /home/user/Nowy_plik
      state: touch
      owner: user
      group: user
      mode: 0777

  - name: Dodanie Folderu
    file:
      path: /home/user/Folder
      state: directory
      owner: user
      group: user
      mode: 0770

  - name: Dodanie wielu fodlerow
    file:
      path: /home/user/Folder/{{ item }}
      state: directory
      owner: user
      group: user
      mode: 0770
    loop:
      - aaa
      - bbb
      - ccc

