---
- name: Copy File Template
  hosts: ubuntu
  become: true
  
  tasks:
  - name: Touch - utworzy nawet jeżeli ścieżka nie istnieje
    file:
      path: /home/user/Nowy_plik
      state: touch
      owner: user
      group: root
      mode: 0700

  - name: File - utworzy tylko gdy ścieżka istnieje, inaczej wyrzuci error
    file:
      path: /home/user/nowy_plik2
      state: file
      owner: user
      group: user
      mode: 0777
    
  - name: Directory - utworzenie foderu
    file:
      path: /home/user/Share
      state: directory
    
  - name: Directory - usunięcie plików lub folderów wskazanych w Loop
    file:
      path: /home/user/{{ item }}
      state: absent
    loop:
      - 4.3CopyFile
      - 4.4add_remove_file
      - index.php
    
  - name: Directory - dodanie plików lub folderów wskazanych w Loop
    file:
      path: /home/user/Share/{{ item }}
      state: directory
    loop:
      - 4.3CopyFile
      - 4.4add_remove_file
      - index.php  
    

          